service: deal-with-it

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    zip: false


package:
  exclude:
    - .data/**
    - env/**
    - .git/**
    - __pycache__/**
    - node_modules/**
    - Dockerfile
    - docker-compose.yml
    - .dockerignore
    - package.json
    - package-lock.json
    - requirements.txt

functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: /
          method: post
          integration: lambda-proxy
